baseURL: http://example.org/
languageCode: en-us
title: Aspose-Purchase
theme: Eclectic-develop
author: 
  facebook: "https://facebook.com/example" 
  twitter: "https://twitter.com/example" 
  email: "contact@example.org" 
  name: "Aspose Pty Ltd" 
  location: Sydney 
  phone: (999) 999-9999 
  hours: "**Mon-Fri:** 9:00AM - 6:00PM, ET" 

menu:
  main: 
    - identifier: about 
      name: About 
      url: /about 
      weight: 100 
    - identifier: contact 
      name: Contact 
      url: /contact 
      weight: 200 
params: 
  color: "#4f46e5"
  copyright: "Copyright &copy; 2022 Aspose Pty Ltd.
    All Rights Reserved."
  footer:
  - title: About
    content: >
      After being founded in 2002, aspose.com was the first website launched by Aspose Pty Ltd which 
      started by offering components for .NET developers. At that time, aspose.com was just a .NET 
      component publisher, building and offering different types of components but later we decided 
      to focus more on components related to file formats (like xls, xlsx, doc, docx, pdf etc.) and grow in that area.
      Now, aspose.com is the market leader offering 20+ file format APIs for different platforms including .NET, Java, 
      C++ and Android, reporting solutions for Microsoft SharePoint and rendering extensions for Microsoft SQL Server 
      Reporting Services and JasperReports with over 21,000 customers (including 80% of Fortune 100 companies) in 135 countries.
  - title: Recent Blog Posts
    recents: blog
    recentCount: 7
  - title: Contact Us
    contact: true